# Generated by Django 5.0.1 on 2024-01-15 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedbooks',
            name='recived_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 15, 12, 13, 5, 956805, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
